import express, { Request, Response, NextFunction } from 'express';
import { randomUUID } from 'crypto';
import { PostgresCompatPool, ResultSetHeader } from './postgresCompat';

type ChatRequest = Request & { chatUser?: number; chatRoom?: string };
export async function installAdminChat(app: express.Express, db: PostgresCompatPool) {
  await db.query(`CREATE TABLE IF NOT EXISTS admin_chat_groups (
    id TEXT PRIMARY KEY, name VARCHAR(80) NOT NULL, owner_id INTEGER NOT NULL REFERENCES users(id),
    member_ids INTEGER[] NOT NULL, client_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(owner_id, client_id))`);
  await db.query(`CREATE TABLE IF NOT EXISTS admin_chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room TEXT NOT NULL, sender_id INTEGER NOT NULL REFERENCES users(id),
    body TEXT NOT NULL DEFAULT '', image_data TEXT, reply_id INTEGER REFERENCES admin_chat_messages(id),
    client_id TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), recalled BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(sender_id, client_id))`);
  await db.query('CREATE INDEX IF NOT EXISTS admin_chat_room_idx ON admin_chat_messages(room, id)');
  await db.query(`CREATE TABLE IF NOT EXISTS admin_chat_reads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room TEXT NOT NULL, reader_id INTEGER NOT NULL REFERENCES users(id), last_id INTEGER NOT NULL DEFAULT 0,
    UNIQUE(room, reader_id))`);
  await db.query(`CREATE TABLE IF NOT EXISTS admin_chat_reactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES admin_chat_messages(id),
    reader_id INTEGER NOT NULL REFERENCES users(id), emoji TEXT NOT NULL,
    UNIQUE(message_id, reader_id))`);

  // Chat is exposed only through the Express API, which performs its own admin
  // and room-membership checks. Block anon/authenticated access through
  // Supabase Data API; the postgres owner used by DATABASE_URL bypasses RLS.
  const chatTables = ['admin_chat_groups', 'admin_chat_messages', 'admin_chat_reads', 'admin_chat_reactions'];
  for (const table of chatTables) {
    await db.query(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY`);
    await db.query(`REVOKE ALL PRIVILEGES ON TABLE ${table} FROM PUBLIC`);
  }
  await db.query(`DO $secure_chat$
    BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE admin_chat_groups, admin_chat_messages, admin_chat_reads, admin_chat_reactions FROM anon';
      END IF;
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE admin_chat_groups, admin_chat_messages, admin_chat_reads, admin_chat_reactions FROM authenticated';
      END IF;
    END
  $secure_chat$`);

  const router = express.Router();
  router.use(async (req: ChatRequest, res: Response, next: NextFunction) => {
    try {
      const token = req.headers.authorization?.match(/^Bearer (.+)$/)?.[1];
      if (!token) return res.status(401).json({ message: 'Vui lòng đăng nhập.' });
      const [rows] = await db.query<any[]>('SELECT id, role, banned FROM users WHERE session_token = ?', [token]);
      if (!rows[0]) return res.status(401).json({ message: 'Phiên đăng nhập đã hết hạn.' });
      if (rows[0].role !== 'admin' || Number(rows[0].banned)) return res.status(403).json({ message: 'Chỉ admin đang hoạt động được sử dụng chat.' });
      req.chatUser = Number(rows[0].id);
      res.setHeader('Cache-Control', 'no-store');
      next();
    } catch (e) { next(e); }
  });
  // Parse images only after authenticating, with a bounded payload.
  router.use(express.json({ limit: '3mb' }));
  router.get('/members', async (_req, res) => {
    const [members] = await db.query("SELECT id, COALESCE(NULLIF(username, ''), name, email) AS name FROM users WHERE role = 'admin' AND COALESCE(banned, 0) = 0 ORDER BY id");
    res.json({ members });
  });
  router.get('/rooms', async (req: ChatRequest, res) => {
    const uid = req.chatUser!;
    const [members] = await db.query<any[]>("SELECT id, COALESCE(NULLIF(username, ''), name, email) AS name FROM users WHERE role = 'admin' AND COALESCE(banned, 0) = 0 AND id <> ? ORDER BY id", [uid]);
    const [groups] = await db.query<any[]>('SELECT id, name, owner_id, member_ids FROM admin_chat_groups WHERE ? = ANY(member_ids) ORDER BY created_at DESC', [uid]);
    const rooms = [{ id: 'general', name: 'Nhóm Admin', memberId: null, memberIds: [uid, ...members.map(m => Number(m.id))], ownerId: null }, ...members.map(m => ({ id: `dm:${Math.min(uid, m.id)}:${Math.max(uid, m.id)}`, name: m.name, memberId: Number(m.id), memberIds: [uid, Number(m.id)], ownerId: null })), ...groups.map(g => ({ id: g.id, name: g.name, memberId: null, memberIds: g.member_ids, ownerId: g.owner_id }))];
    const [latest] = await db.query<any[]>(`SELECT DISTINCT ON (room) room, id, body, image_data IS NOT NULL AS has_image, recalled, created_at, sender_id FROM admin_chat_messages WHERE room = ANY(?::text[]) ORDER BY room, id DESC`, [rooms.map(r => r.id)]);
    const [counts] = await db.query<any[]>(`SELECT m.room, COUNT(*) AS unread FROM admin_chat_messages m LEFT JOIN admin_chat_reads r ON r.room = m.room AND r.reader_id = ? WHERE m.room = ANY(?::text[]) AND m.sender_id <> ? AND m.id > COALESCE(r.last_id, 0) GROUP BY m.room`, [uid, rooms.map(r => r.id), uid]);
    res.json({ rooms: rooms.map(r => ({ ...r, last: latest.find(m => m.room === r.id) || null, unread: Number(counts.find(c => c.room === r.id)?.unread || 0) })) });
  });
  async function validMembers(value: unknown): Promise<number[] | null> {
    if (!Array.isArray(value) || !value.length || value.length > 100 || value.some(id => !Number.isSafeInteger(id) || id < 1 || id > 2147483647)) return null;
    const ids = [...new Set(value)] as number[];
    const [rows] = await db.query<any[]>("SELECT id FROM users WHERE id = ANY(?::int[]) AND role = 'admin' AND COALESCE(banned, 0) = 0", [ids]);
    return rows.length === ids.length ? ids : null;
  }
  router.post('/groups', async (req: ChatRequest, res) => {
    const { name, memberIds, clientId } = req.body || {};
    if (typeof name !== 'string' || !name.trim() || name.trim().length > 80 || /[\u0000-\u001f]/.test(name) || typeof clientId !== 'string' || !/^[a-zA-Z0-9_-]{8,80}$/.test(clientId)) return res.status(400).json({ message: 'Nhập tên nhóm từ 1 đến 80 ký tự.' });
    const ids = await validMembers(memberIds);
    if (!ids || !ids.some(id => id !== req.chatUser)) return res.status(400).json({ message: 'Chọn ít nhất một admin khác đang hoạt động (tối đa 100 người).' });
    await db.query('INSERT INTO admin_chat_groups(id, name, owner_id, member_ids, client_id) VALUES (?, ?, ?, ?, ?) ON CONFLICT(owner_id, client_id) DO NOTHING', [`group:${randomUUID()}`, name.trim(), req.chatUser, [...new Set([req.chatUser!, ...ids])], clientId]);
    const [rows] = await db.query<any[]>('SELECT id FROM admin_chat_groups WHERE owner_id = ? AND client_id = ?', [req.chatUser, clientId]);
    res.status(201).json({ id: rows[0].id });
  });
  router.use('/rooms/:room', async (req: ChatRequest, res, next) => {
    const room = String(req.params.room);
    if (room.startsWith('group:')) {
      const [groups] = await db.query<any[]>('SELECT id FROM admin_chat_groups WHERE id = ? AND ? = ANY(member_ids)', [room, req.chatUser]);
      if (!groups.length) return res.status(403).json({ message: 'Bạn không phải thành viên nhóm này.' });
    } else if (room !== 'general') {
      const match = /^dm:([1-9]\d*):([1-9]\d*)$/.exec(room);
      if (!match || Number(match[1]) >= Number(match[2]) || !match.slice(1).map(Number).includes(req.chatUser!)) return res.status(403).json({ message: 'Không có quyền truy cập hội thoại.' });
      const [members] = await db.query<any[]>("SELECT id FROM users WHERE id = ANY(?::int[]) AND role = 'admin' AND COALESCE(banned, 0) = 0", [[Number(match[1]), Number(match[2])]]);
      if (members.length !== 2) return res.status(403).json({ message: 'Thành viên không còn quyền admin.' });
    }
    req.chatRoom = room;
    next();
  });
  router.post('/rooms/:room/members', async (req: ChatRequest, res) => {
    const [groups] = await db.query<any[]>('SELECT owner_id FROM admin_chat_groups WHERE id = ?', [req.chatRoom]);
    if (!groups.length || groups[0].owner_id !== req.chatUser) return res.status(403).json({ message: 'Chỉ người tạo nhóm được thêm thành viên.' });
    const ids = await validMembers(req.body?.memberIds);
    if (!ids) return res.status(400).json({ message: 'Chỉ được thêm admin đang hoạt động.' });
    await db.query('UPDATE admin_chat_groups SET member_ids = ARRAY(SELECT DISTINCT unnest(member_ids || ?::int[])) WHERE id = ?', [ids, req.chatRoom]);
    res.json({ ok: true });
  });
  router.get('/rooms/:room/messages', async (req: ChatRequest, res) => {
    const before = Number(req.query.before) || 2147483647;
    if (!Number.isSafeInteger(before) || before < 1 || before > 2147483647) return res.status(400).json({ message: 'Mốc lịch sử không hợp lệ.' });
    const ids = typeof req.query.ids === 'string' ? req.query.ids.split(',').map(Number) : null;
    if (ids && (!ids.length || ids.length > 200 || ids.some(id => !Number.isSafeInteger(id) || id < 1 || id > 2147483647))) return res.status(400).json({ message: 'Danh sách tin nhắn không hợp lệ.' });
    const [messages] = await db.query<any[]>(`SELECT m.id, m.sender_id, m.body, m.recalled, m.created_at, m.reply_id, m.image_data IS NOT NULL AS has_image,
      COALESCE(NULLIF(u.username, ''), u.name, u.email) AS sender_name,
      CASE WHEN p.recalled THEN 'Tin nhắn đã thu hồi' ELSE p.body END AS reply_body,
      p.image_data IS NOT NULL AS reply_image,
      COALESCE((SELECT json_agg(json_build_object('userId', reader_id, 'emoji', emoji)) FROM admin_chat_reactions WHERE message_id = m.id), '[]'::json) AS reactions
      FROM admin_chat_messages m JOIN users u ON u.id = m.sender_id LEFT JOIN admin_chat_messages p ON p.id = m.reply_id
      WHERE m.room = ? AND ${ids ? 'm.id = ANY(?::int[])' : 'm.id < ?'} ORDER BY m.id DESC ${ids ? '' : 'LIMIT 41'}`, [req.chatRoom, ids || before]);
    const [reads] = await db.query('SELECT reader_id, last_id FROM admin_chat_reads WHERE room = ?', [req.chatRoom]);
    res.json({ messages: (ids ? messages : messages.slice(0, 40)).reverse(), hasMore: !ids && messages.length > 40, reads });
  });
  router.post('/rooms/:room/messages', async (req: ChatRequest, res) => {
    const { body = '', image = null, replyId = null, clientId } = req.body || {};
    if (typeof body !== 'string' || body.length > 5000 || typeof clientId !== 'string' || !/^[a-zA-Z0-9_-]{8,80}$/.test(clientId)) return res.status(400).json({ message: 'Tin nhắn không hợp lệ (tối đa 5.000 ký tự).' });
    if (!body.trim() && !image) return res.status(400).json({ message: 'Nhập tin nhắn hoặc chọn ảnh.' });
    if (image !== null) {
      if (typeof image !== 'string' || image.length > 2800000) return res.status(400).json({ message: 'Ảnh phải nhỏ hơn 2 MB.' });
      const match = /^data:image\/(jpeg|png|gif|webp);base64,([A-Za-z0-9+/]+={0,2})$/.exec(image);
      if (!match) return res.status(400).json({ message: 'Chỉ hỗ trợ ảnh JPEG, PNG, GIF hoặc WebP.' });
      const bytes = Buffer.from(match[2], 'base64');
      const type = match[1];
      const valid = type === 'jpeg' ? bytes.subarray(0, 3).equals(Buffer.from([255,216,255])) : type === 'png' ? bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])) : type === 'gif' ? /^GIF8[79]a/.test(bytes.subarray(0,6).toString()) : bytes.subarray(0,4).toString() === 'RIFF' && bytes.subarray(8,12).toString() === 'WEBP';
      if (!valid || bytes.length > 2 * 1024 * 1024) return res.status(400).json({ message: 'Ảnh không hợp lệ hoặc lớn hơn 2 MB.' });
    }
    if (replyId !== null) {
      if (!Number.isSafeInteger(replyId)) return res.status(400).json({ message: 'Tin trả lời không hợp lệ.' });
      const [reply] = await db.query<any[]>('SELECT id FROM admin_chat_messages WHERE id = ? AND room = ?', [replyId, req.chatRoom]);
      if (!reply.length) return res.status(400).json({ message: 'Không tìm thấy tin nhắn để trả lời.' });
    }
    const [result] = await db.query<ResultSetHeader>(`INSERT INTO admin_chat_messages(room, sender_id, body, image_data, reply_id, client_id) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (sender_id, client_id) DO NOTHING`, [req.chatRoom, req.chatUser, body.trim(), image, replyId, clientId]);
    res.status(201).json({ id: result.insertId });
  });
  router.get('/rooms/:room/messages/:id/image', async (req: ChatRequest, res) => {
    const [rows] = await db.query<any[]>('SELECT image_data FROM admin_chat_messages WHERE id = ? AND room = ? AND recalled = FALSE', [req.params.id, req.chatRoom]);
    if (!rows[0]?.image_data) return res.status(404).json({ message: 'Ảnh không còn tồn tại.' });
    res.json({ image: rows[0].image_data });
  });
  router.post('/rooms/:room/read', async (req: ChatRequest, res) => {
    const id = req.body?.lastId;
    if (!Number.isSafeInteger(id) || id < 1) return res.status(400).json({ message: 'Mốc đọc không hợp lệ.' });
    const [rows] = await db.query<any[]>('SELECT id FROM admin_chat_messages WHERE room = ? AND id = ?', [req.chatRoom, id]);
    if (!rows.length) return res.status(400).json({ message: 'Không tìm thấy tin nhắn.' });
    await db.query(`INSERT INTO admin_chat_reads(room, reader_id, last_id) VALUES (?, ?, ?) ON CONFLICT(room, reader_id) DO UPDATE SET last_id = GREATEST(admin_chat_reads.last_id, EXCLUDED.last_id)`, [req.chatRoom, req.chatUser, id]);
    res.json({ ok: true });
  });
  router.delete('/rooms/:room/messages/:id', async (req: ChatRequest, res) => {
    const [result] = await db.query<ResultSetHeader>("UPDATE admin_chat_messages SET recalled = TRUE, body = '', image_data = NULL WHERE id = ? AND room = ? AND sender_id = ?", [req.params.id, req.chatRoom, req.chatUser]);
    if (!result.affectedRows) return res.status(403).json({ message: 'Chỉ được thu hồi tin nhắn của mình.' });
    res.json({ ok: true });
  });
  router.put('/rooms/:room/messages/:id/reaction', async (req: ChatRequest, res) => {
    const emoji = req.body?.emoji;
    if (!['👍', '❤️', '😂', '😮', '😢', ''].includes(emoji)) return res.status(400).json({ message: 'Cảm xúc không hợp lệ.' });
    const [rows] = await db.query<any[]>('SELECT id FROM admin_chat_messages WHERE id = ? AND room = ? AND recalled = FALSE', [req.params.id, req.chatRoom]);
    if (!rows.length) return res.status(404).json({ message: 'Tin nhắn không còn tồn tại.' });
    if (!emoji) await db.query('DELETE FROM admin_chat_reactions WHERE message_id = ? AND reader_id = ?', [req.params.id, req.chatUser]);
    else await db.query('INSERT INTO admin_chat_reactions(message_id, reader_id, emoji) VALUES (?, ?, ?) ON CONFLICT(message_id, reader_id) DO UPDATE SET emoji = EXCLUDED.emoji', [req.params.id, req.chatUser, emoji]);
    res.json({ ok: true });
  });
  router.use((err: any, _req: Request, res: Response, _next: NextFunction) => {
    console.error('Admin chat:', err.message);
    res.status(err.status === 413 ? 413 : 500).json({ message: err.status === 413 ? 'Ảnh quá lớn. Vui lòng chọn ảnh dưới 2 MB.' : 'Không thể xử lý chat. Vui lòng thử lại.' });
  });
  app.use('/admin/chat', router);
}
