$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$dataDir = Join-Path $root 'data'
$output = Join-Path $dataDir 'supabase_migration.sql'

$schema = @'
begin;

drop table if exists "bulk_order_items", "bulk_orders", "order_items", "orders", "user_vip_history", "user_tokens", "otp_codes", "promotions", "vip_tiers", "categories", "products", "users_backup", "users" cascade;

create table "users" (
  "id" integer generated by default as identity primary key,
  "name" varchar(100) not null,
  "email" varchar(150) not null unique,
  "phone" varchar(20) not null,
  "password" varchar(255) not null,
  "created_at" timestamp default current_timestamp,
  "username" varchar(100), "address" text, "is_verified" smallint default 0,
  "updated_at" timestamp default current_timestamp, "role" varchar(20) default 'user',
  "banned" smallint default 0, "vipTier" varchar(20), "quarterlySpending" decimal(12,2) default 0,
  "rewardPoints" decimal(12,2) default 0, "vipQuarterKey" varchar(20), "vipTierUpdatedAt" timestamp
);
create table "users_backup" (
  "id" integer not null, "name" varchar(100) not null, "email" varchar(150) not null,
  "phone" varchar(20) not null, "password" varchar(255) not null, "created_at" timestamp default current_timestamp,
  "username" varchar(100), "address" text, "is_verified" smallint default 0,
  "updated_at" timestamp default current_timestamp, "role" varchar(20) default 'user', "banned" smallint default 0
);
create table "products" (
  "id" integer generated by default as identity primary key, "name" varchar(100), "price" varchar(20),
  "oldPrice" varchar(20), "cat" varchar(50), "imageUrl" varchar(255), "isFlashSale" smallint default 0,
  "salePrice" varchar(20), "priceValue" integer default 0
);
create table "categories" (
  "id" integer generated by default as identity primary key, "name" varchar(100) not null,
  "slug" varchar(100) not null unique, "imageUrl" varchar(255), "createdAt" timestamp default current_timestamp
);
create table "orders" (
  "id" integer generated by default as identity primary key, "userId" integer references "users"("id"),
  "totalAmount" decimal(10,2), "status" varchar(50) default 'pending', "createdAt" timestamp default current_timestamp,
  "address" varchar(500), "note" text, "orderCode" varchar(50), "paymentMethod" varchar(100),
  "shippingAddress" varchar(500), "estimatedDelivery" date, "updatedAt" timestamp default current_timestamp
);
create table "order_items" (
  "id" integer generated by default as identity primary key, "orderId" integer not null references "orders"("id"),
  "productId" integer not null references "products"("id"), "productName" varchar(255),
  "price" decimal(10,2), "quantity" integer, "note" text
);
create table "bulk_orders" (
  "id" integer generated by default as identity primary key, "userId" integer not null references "users"("id"),
  "orderCode" varchar(50) not null, "orderDate" varchar(50), "totalPrice" decimal(15,2) default 0,
  "status" varchar(20) default 'pending', "createdAt" timestamp default current_timestamp
);
create table "bulk_order_items" (
  "id" integer generated by default as identity primary key, "bulkOrderId" integer not null references "bulk_orders"("id"),
  "productId" varchar(50), "productName" varchar(255), "kg" decimal(10,2),
  "pricePerKg" decimal(15,2), "subtotal" decimal(15,2), "note" text
);
create table "otp_codes" (
  "id" integer generated by default as identity primary key, "phone" varchar(20), "otp_code" varchar(6),
  "expires_at" timestamp, "created_at" timestamp default current_timestamp
);
create table "promotions" (
  "id" integer generated by default as identity primary key, "code" varchar(50) not null unique,
  "description" varchar(255), "discountType" varchar(20) default 'percent' check ("discountType" in ('percent','fixed')),
  "discountValue" decimal(10,2) default 0, "minOrderValue" decimal(10,2) default 0,
  "maxUsage" integer default 0, "usedCount" integer default 0, "startDate" date, "endDate" date,
  "isActive" smallint default 1, "createdAt" timestamp default current_timestamp, "updatedAt" timestamp default current_timestamp
);
create table "user_tokens" (
  "token" varchar(255) primary key, "userId" integer not null, "createdAt" timestamp default current_timestamp
);
create table "user_vip_history" (
  "id" integer generated by default as identity primary key, "user_id" integer not null references "users"("id") on delete cascade,
  "cycle_key" varchar(20) not null, "tier_key" varchar(20), "spending" decimal(12,2) default 0,
  "points_earned" decimal(12,2) default 0, "changed_at" timestamp default current_timestamp
);
create table "vip_tiers" (
  "id" integer generated by default as identity primary key, "tier_key" varchar(20) not null unique,
  "label" varchar(50) not null, "min_spending" decimal(12,2) not null,
  "discount_percent" decimal(5,2) not null default 0, "points_multiplier" decimal(5,2) not null default 1,
  "created_at" timestamp default current_timestamp, "updated_at" timestamp default current_timestamp
);
'@

$order = @(
  'dalatshop_users.sql', 'dalatshop_users_backup.sql', 'dalatshop_products.sql', 'dalatshop_categories.sql',
  'dalatshop_orders.sql', 'dalatshop_order_items.sql', 'dalatshop_bulk_orders.sql', 'dalatshop_bulk_order_items.sql',
  'dalatshop_otp_codes.sql', 'dalatshop_promotions.sql', 'dalatshop_user_tokens.sql',
  'dalatshop_user_vip_history.sql', 'dalatshop_vip_tiers.sql'
)

$inserts = foreach ($name in $order) {
  $raw = Get-Content -Raw -Encoding UTF8 (Join-Path $dataDir $name)
  [regex]::Matches($raw, '(?ms)^INSERT INTO `[^`]+` VALUES .*?;') | ForEach-Object {
    $_.Value.Replace('`', '"').Replace('\n', "`n")
  }
}

$sequences = @'

select setval(pg_get_serial_sequence('users','id'), coalesce(max("id"),1), true) from "users";
select setval(pg_get_serial_sequence('products','id'), coalesce(max("id"),1), true) from "products";
select setval(pg_get_serial_sequence('categories','id'), coalesce(max("id"),1), true) from "categories";
select setval(pg_get_serial_sequence('orders','id'), coalesce(max("id"),1), true) from "orders";
select setval(pg_get_serial_sequence('order_items','id'), coalesce(max("id"),1), true) from "order_items";
select setval(pg_get_serial_sequence('bulk_orders','id'), coalesce(max("id"),1), true) from "bulk_orders";
select setval(pg_get_serial_sequence('bulk_order_items','id'), coalesce(max("id"),1), true) from "bulk_order_items";
select setval(pg_get_serial_sequence('otp_codes','id'), coalesce(max("id"),1), true) from "otp_codes";
select setval(pg_get_serial_sequence('promotions','id'), coalesce(max("id"),1), true) from "promotions";
select setval(pg_get_serial_sequence('user_vip_history','id'), coalesce(max("id"),1), true) from "user_vip_history";
select setval(pg_get_serial_sequence('vip_tiers','id'), coalesce(max("id"),1), true) from "vip_tiers";

commit;
'@

Set-Content -Path $output -Value ($schema + "`n" + ($inserts -join "`n") + $sequences) -Encoding UTF8
Write-Output $output
